[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run dev"
  functions = "functions"
  publish = "dist"

[redirects]
  from = "/bottlenecks"
  to = "/"
  status = 200
  force = false

  conditions = {Path = {exclude = ["/.netlify/functions/*"]}}