[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  functions = "netlify/functions"
  publish = "dist"

# Redirect only for SPA routing - excluding Netlify Functions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  # Don't redirect to index.html for Netlify function calls
  conditions = {Path = {exclude = ["/.netlify/functions/*"]}}