[build]
  command = "npm run build:clean"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run dev"
  functions = "functions"
  publish = "dist"

# Redirect for client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

  conditions = {Path = {exclude = ["/.netlify/functions/*"]}}